import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import HeaderNav from "./components/HeaderNav";
import Toast from "./components/Toast";
import SideNavBar from "./components/SideNavBar";
import { ThemeContextProvider } from "./context/theme";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Resource Kit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* title and search box */}
        <SessionProvider session={session}>
          <HeaderNav />
          {/* <ShowToastContext.Provider> */}
          <main className="min-w-screen min-h-screen lg:mx-32 ">
            <ThemeContextProvider>{children}</ThemeContextProvider>
          </main>
        </SessionProvider>
        {/* </ShowToastContext.Provider> */}
        <Footer />
      </body>
    </html>
  );
}
